
TOPLEVEL_LANG = verilog

#COMPILE_ARGS=-pfileline=1

NETFPGA_HW_LIB=$(SUME_FOLDER)/lib/hw/std/cores

# Verilog source files
VERILOG_SOURCES = ../../hdl/timer_module.v

TOPLEVEL = timer_module
MODULE = test_timer_module

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim

